apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: test-app
        image: docker.pkg.github.com/t-shiotani/alibabacontainer/app:v2.1
        ports:
        - containerPort: 8080
